services:
  db:
    image: mysql:8.0
    container_name: mysql_webapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: webappuser
      MYSQL_PASSWORD: webapppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: